### ISSUE TITLE
Drawer doesn't show up anymore after clicking outside 

### ISSUE THREAD

**Issue by hadnet** [lukebrandonfarrell/react-native-navigation-drawer-extension#1] opened 2019-02-23 07:50 UTC
This issue happens on Android only (I'm using Android 9.0 x86). I register the drawer component and I click to open it (using a button component with showDrawer()). Drawer shows up ok. Then I click outside just to dismiss the drawer and everything is ok again. But when I click to open the drawer again, it doesn't work anymore,  I mean it doesn't show up. Nothing happens, it's like the drawer is freeze or something.

**Comment by lukebrandonfarrell** [comment] 2019-02-26 17:06
@hadnet 

Thanks for flagging this up, I was able to replicate this on Android.

I'll be publishing a fix to this in the morning.

**Comment by lukebrandonfarrell** [comment] 2019-02-27 09:06
@hadnet This has been fixed in react-native-navigation-drawer-extension@1.0.2.

**Closed by lukebrandonfarrell** 2019-02-27 09:06 UTC
Labels: android, bug

**Comment by ClementDidier** [comment] 2019-02-28 18:10
I have the same issue on Android 7.0 with the new version 1.0.2. The drawer appears and hides once. After that, all my application is frozen and the following warning is stacked when I press a user interface object: "Possible Unhandled Promise Rejection (id: [...]): Error: nothing to dismiss [...]"

**Comment by lukebrandonfarrell** [comment] 2019-03-02 17:29
@ClementDidier This should be fixed in version 1.0.2. Make sure you have that installed, you can check your node_modules folder and make sure line 171 of `RNNDrawer.js` is `Navigation.dismissOverlay(this.props.componentId);` and not `Navigation.dismissModal(this.props.componentId);`. This was the cause of the problem.

Let me know if you are still experiencing the issue.
